[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lecture_3"
version = "0.1.0"
description = "Innowise Lecture 3"
authors = [{ name = "Andrei Ishchanka" }]
requires-python = ">=3.10"