[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lecture_2"
version = "0.1.0"
description = "Innowise Lecture 2"
authors = [{ name = "Andrei Ishchanka" }]
requires-python = ">=3.10"